### ISSUE TITLE
Inherited Code

### ISSUE THREAD

**Issue by rahulsrivastava1** [rahulsrivastava1/Hackerrank-Cplus-solutions#2]

**Comment by Pranav2442** [comment]
Hello I have this issue,please have a look on the code ...Thanks

**Comment by rahulsrivastava1** [comment]
@Pranav2442 please create pull request

**Comment by Pranav2442** [comment]
created

**Comment by rahulsrivastava1** [comment]
@Pranav2442 I haven't received any pull requests, please give me the link!

**Comment by rahulsrivastava1** [comment]
@Pranav2442 by the way I have a question, how do you find my repository?

**Comment by Pranav2442** [comment]
I found it in the "fewer fork" section

**Comment by Pranav2442** [comment]
I'm trying to push the solution of hotel prices issue but I'm unable to do it

**Comment by rahulsrivastava1** [comment]
@Pranav2442 how many have you completed pull requests for hacktoberfest?

**Comment by rahulsrivastava1** [comment]
@Pranav2442 and also is it possible to contribute 4 pull requests in the same repository to qualify for hacktoberfest?

**Comment by rahulsrivastava1** [comment]
@Pranav2442 i din't understand fewer fork section... Can you send me a screenshot?

**Comment by rahulsrivastava1** [comment]
> I'm trying to push the solution of hotel prices issue but I'm unable to do it

Done! 🔥🌟

**Comment by Pranav2442** [comment]
I don't know why It is not reflecting on my hacktoberfest profile even after contribution
![WhatsApp Image 2021-10-01 at 1 20 21 PM (1)](https://user-images.githubusercontent.com/74892541/135586644-fa675ca7-c621-4e1b-a27b-701107806921.jpeg)
![WhatsApp Image 2021-10-01 at 1 20 21 PM](https://user-images.githubusercontent.com/74892541/135586649-c1732570-9a1a-48a1-8887-0e7c489d63ab.jpeg)

**Comment by Pranav2442** [comment]
Yes I think we can contribute to a single repo

**Comment by rahulsrivastava1** [comment]
Let me inform when you have in progress all 4

**Comment by rahulsrivastava1** [comment]
it is showing error na?

**Comment by Pranav2442** [comment]
yes I'll inform once I'm done

**Comment by Pranav2442** [comment]
yes it is showing error on hacktoberfest website even after the merge too

**Comment by rahulsrivastava1** [comment]
@Pranav2442 Are you sure that we can contribute to same repo 4 valid pull requests in a single day?

**Comment by Pranav2442** [comment]
No I'm not sure

**Comment by rahulsrivastava1** [comment]
ok
